#pragma once
#ifndef EXMACRO_H
#define EXMACRO_H

#define EXLIB_FOR_ALL_COMP_OPS_H(MACRO_NAME) MACRO_NAME(<) MACRO_NAME(>) MACRO_NAME(<=) MACRO_NAME(>=) MACRO_NAME(==) MACRO_NAME(!=)
#define EXLIB_FOR_ALL_COMP_OPS(MACRO_NAME) EXLIB_FOR_ALL_COMP_OPS_H(MACRO_NAME)

#endif